### ISSUE TITLE
Support multiple Draw.io cli options

### ISSUE THREAD

**Issue by rlespinasse** [rlespinasse/drawio-export#19]
If I want to use multiple options on the Draw.io CLI, I have the following error messages

```shell
docker run -t -v $(pwd):/data rlespinasse/drawio-export:2.3.0 -E png -C '-t -e'
+ export file : ./tests/data/in/file1.drawio
++ prepare export folder : ./tests/data/in/export
++ cleanup export content : ./tests/data/in/export/file1*
++ export page 1 : Page-1
+++ generate png file
Error: input file/directory not found
...
```

Or 

```shell
docker run -t -v $(pwd):/data rlespinasse/drawio-export:2.3.0 -E png -C -t -e
/drawio/drawio-export.sh: invalid option -- 'e'
...
```

**Comment by danquah** [comment]
Btw, I suspect this could be addressed by #29 :)

**Comment by rlespinasse** [comment]
I test it against the v3.0.0 and this continue to fail 😄,
I think it's more an issue on the `getopt` try to manage some string with space.

**Comment by danquah** [comment]
Ah well, it was worth the try :)

**Comment by rlespinasse** [comment]
`getopt` split on space, so the cli need to move from `-C '-t -e'` to ` -C -t -C -e` to be able to work.

Plan of actions
- map each `drawio cli` argument to a similar `drawio export` argument
- mark as deprecated the `-C` and `--cli-options` arguments
