### ISSUE TITLE
Azure shapes doesn't draw

### ISSUE THREAD

**Issue by XBeg9** [rlespinasse/drawio-export#47]
Thanks for the great Docker, but I am facing an issue by using Azure shapes inside draw.io.

That's my original screen from mac: 

<img width="527" alt="schema drawio — microstacks 2020-12-18 13-11-12" src="https://user-images.githubusercontent.com/872907/102608416-82967200-4132-11eb-93b2-287dd49cb91c.png">

And that's what `drawio-export` has drawn so far:

![schema-main](https://user-images.githubusercontent.com/872907/102608477-980b9c00-4132-11eb-9395-432748f67d72.png)

Attaching my [drawio file](https://gofile.io/d/zG1cy0) here for debug purposes.

**Comment by XBeg9** [comment]
![Untitled Diagram drawio - diagrams net 2020-12-18 13-14-59](https://user-images.githubusercontent.com/872907/102608744-0fd9c680-4133-11eb-9fc8-b4ce3a602f0e.png)

that's how you can enable it inside drawio

**Comment by rlespinasse** [comment]
Currently, this feature is not supported. I will have a look at it.

**Comment by rlespinasse** [comment]
Shape are correctly exported, only Azure shape seem to have an issue during export.

**Comment by rlespinasse** [comment]
Seem to be linked to an licence issue jgraph/drawio#1058

**Comment by rlespinasse** [comment]
In the latest version drawio, the licence issue is resolved. drawio-cli and drawio-export have been updated.
