### ISSUE TITLE
drawio-export fails silently

### ISSUE THREAD

**Issue by ptr33** [rlespinasse/drawio-export#73]
Hi,

I was using the example from the documentation but there is no output file created.
I used a very basic drawio file, and the output directory is correctly created but it stays empty.

The command I used is
```bash
$ docker run --rm -it -v $(pwd):/data rlespinasse/drawio-export 
+ export file : untitled.drawio
```
There is no further output after this.

The drawio file
```xml
<mxGraphModel dx="325" dy="652" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="827" pageHeight="1169" background="#ffffff"><root><mxCell id="0"/><mxCell id="1" parent="0"/><mxCell id="2" value="" style="rounded=0;whiteSpace=wrap;html=1;" vertex="1" parent="1"><mxGeometry x="10" y="10" width="120" height="60" as="geometry"/></mxCell></root></mxGraphModel>
```

Getting the version with - V shows drawio-exporter 1.1.0

What did I do wrong?

Thank you

**Comment by ptr33** [comment]
Additional comment to my previous e-mail:
Using drawio files generated by the application from https://www.diagrams.net/ works as expected and properly generates the output files. Only draw.io files generated by jupyterlab-drawio causes above behavior.

It would be nice if the tool generates an error if a draw.io file is used, which is not compatible.

Thank you

**Comment by rlespinasse** [comment]
From what I see, the jupyterlab-drawio seem to only generate you the graph model without the wrapper to have a valid drawio file.

The bug part is for the missing log when a file is not valid.
The enhancement part is to help support this kind of output.

Thanks for the report.
