### ISSUE TITLE
Example not working on my machine

### ISSUE THREAD

**Issue by fpgdesa** [rlespinasse/drawio-export#74]
Hi! I found the following error:

* I downloaded the `file1.drawio` from `test/data` folder

```shell
$ sudo docker run -it -v $(pwd):/data rlespinasse/drawio-export
+ export file : ./file1.drawio
++ export page 1 : Page-1
+++ generate pdf file
error: Found argument 'export' which wasn't expected, or isn't valid in this context

USAGE:
    drawio-exporter --drawio-desktop-headless

For more information try --help
```

Thanks!

**Comment by rlespinasse** [comment]
<img width="474" alt="Capture d’écran 2022-07-26 à 20 35 15" src="https://user-images.githubusercontent.com/1280212/181085125-b2271bfc-1c38-4e3d-8d33-3dd65531c54e.png">

I can't reproduce your bug. Can you reproduce it and get a screenshot of your try.
