### ISSUE TITLE
Support for Apple Silicon

### ISSUE THREAD

**Issue by ross-paypay** [rlespinasse/drawio-export#80]
I'm having some issues when running on my Apple M1 Macbook Pro.

I'm getting the following output:
```
> docker run -it -v $(pwd):/app -w /app rlespinasse/drawio-export docs -o docs/drawio/generated
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
+ export file : drawio/example.drawio
++ export page 1 : Page-1
+++ generate pdf file
Error: fail to export using draw.io desktop
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
qemu: unknown option 'type=utility'
qemu: unknown option 'type=renderer'
[22:1020/024656.544583:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped

```

**Comment by rlespinasse** [comment]
To be able to support apple silicon, the base image needs to also support Apple Silicon. This is the reason for rlespinasse/docker-drawio-desktop-headless#30.

I recently gained access to an Apple Silicon and I confirm this issue. 

Some Linux images can run on Apple Silicon, but the latest and the previous versions are concerned, I presume the other versions are also impacted.

**Comment by swill** [comment]
Thank you SOO much for this feature release.  I have been missing the ability to use your tool after moving from linux to mac.  ❤️

**Comment by rlespinasse** [comment]
@swill thanks you for your kind words

Finally, the key to success for this support was to wait for Drawio-desktop to support Apple Silicon itself 😄.
