### ISSUE TITLE
Font support

### ISSUE THREAD

**Issue by temmeand** [rlespinasse/drawio-export#84]
Is there a way to provide additional fonts to drawio in the docker container?

I've seen in the jgraph docker container binds the system fonts folder
(https://github.com/jgraph/docker-drawio/tree/dev/image-export).

If not, what is the default font or supported fonts? (I'm not sure how to dig into the Docker image to determine this myself. Does it just use the system fonts of the Docker image or is there something else?)

**Comment by rlespinasse** [comment]
We do not customize the fonts part yet.
So it's the default system fonts, I presume.

If you want to dig it, this image is based on the docker image https://github.com/rlespinasse/docker-drawio-desktop-headless with serving Drawio Desktop in a headless mode and the root image is `debian:bullseye`.

**Comment by rlespinasse** [comment]
Since [rlespinasse/drawio-export:v4.8.0](https://github.com/rlespinasse/drawio-export/releases/tag/v4.8.0), the docker image support multiple additional fonts (list [here](https://github.com/rlespinasse/drawio-export#additional-fonts))
